// Generated by Wrangler by running `wrangler types`

interface Env {
  MCP_OBJECT: DurableObjectNamespace<import("./src/index.js").RecipeMCP>;
  OAUTH_KV: KVNamespace;
  CF_VERSION_METADATA: WorkerVersionMetadata;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  COOKIE_ENCRYPTION_KEY: string;
  RECIPE_API_BASE_URL: string;
  RECIPE_API_KEY: string;
  SENTRY_DSN?: string;
  ENVIRONMENT?: string;
}
