export function getMealTypeEmoji(mealType: string): string {
  const mealTypeEmojis: { [key: string]: string } = {
    breakfast: "🍳",
    dinner: "🍽️",
    lunch: "🥪",
    snack: "🍿",
    dessert: "🍰",
    drinks: "🍹",
  };

  return mealTypeEmojis[mealType.toLowerCase()] || "🍴";
}

export function getCuisineTypeEmoji(cuisineType: string): string {
  const cuisineTypeEmojis: { [key: string]: string } = {
    afghan: "🇦🇫",
    african: "🌍",
    algerian: "🇩🇿",
    american: "🇺🇸",
    angolan: "🇦🇴",
    argentinian: "🇦🇷",
    australian: "🇦🇺",
    austrian: "🇦🇹",
    bahamian: "🇧🇸",
    bahraini: "🇧🇭",
    bangladeshi: "🇧🇩",
    belgian: "🇧🇪",
    brazilian: "🇧🇷",
    british: "🇬🇧",
    cambodian: "🇰🇭",
    canadian: "🇨🇦",
    caribbean: "🏝️",
    chilean: "🇨🇱",
    chinese: "🇨🇳",
    colombian: "🇨🇴",
    costa_rican: "🇨🇷",
    cuban: "🇨🇺",
    dominican: "🇩🇴",
    ecuadorian: "🇪🇨",
    egyptian: "🇪🇬",
    ethiopian: "🇪🇹",
    filipino: "🇵🇭",
    french: "🇫🇷",
    german: "🇩🇪",
    greek: "🇬🇷",
    guatemalan: "🇬🇹",
    haitian: "🇭🇹",
    hawaiian: "🌺",
    honduran: "🇭🇳",
    hungarian: "🇭🇺",
    indian: "🇮🇳",
    indonesian: "🇮🇩",
    iranian: "🇮🇷",
    iraqi: "🇮🇶",
    irish: "🇮🇪",
    israeli: "🇮🇱",
    italian: "🇮🇹",
    jamaican: "🇯🇲",
    japanese: "🇯🇵",
    korean: "🇰🇷",
    lebanese: "🇱🇧",
    malaysian: "🇲🇾",
    mediterranean: "🌊",
    mexican: "🇲🇽",
    moroccan: "🇲🇦",
    nepalese: "🇳🇵",
    new_zealander: "🇳🇿",
    nigerian: "🇳🇬",
    norwegian: "🇳🇴",
    pakistani: "🇵🇰",
    panamanian: "🇵🇦",
    peruvian: "🇵🇪",
    polish: "🇵🇱",
    portuguese: "🇵🇹",
    puerto_rican: "🇵🇷",
    romanian: "🇷🇴",
    russian: "🇷🇺",
    salvadoran: "🇸🇻",
    saudi: "🇸🇦",
    singaporean: "🇸🇬",
    south_african: "🇿🇦",
    spanish: "🇪🇸",
    sri_lankan: "🇱🇰",
    swedish: "🇸🇪",
    swiss: "🇨🇭",
    taiwanese: "🇹🇼",
    thai: "🇹🇭",
    turkish: "🇹🇷",
    ukrainian: "🇺🇦",
    uruguayan: "🇺🇾",
    venezuelan: "🇻🇪",
    vietnamese: "🇻🇳",
  };

  return cuisineTypeEmojis[cuisineType.toLowerCase()] || "🌍";
}
