export const CUISINE_TYPES = [
  { value: "afghan", label: "Afghan" },
  { value: "african", label: "African" },
  { value: "algerian", label: "Algerian" },
  { value: "american", label: "American" },
  { value: "angolan", label: "Angolan" },
  { value: "anguillan", label: "Anguillan" },
  { value: "antiguan", label: "Antiguan" },
  { value: "argentinian", label: "Argentinian" },
  { value: "aruban", label: "Aruban" },
  { value: "ascension_islander", label: "Ascension Islander" },
  { value: "australian", label: "Australian" },
  { value: "austrian", label: "Austrian" },
  { value: "bahamian", label: "Bahamian" },
  { value: "bahraini", label: "Bahraini" },
  { value: "bangladeshi", label: "Bangladeshi" },
  { value: "barbadian", label: "Barbadian" },
  { value: "barbudan", label: "Barbudan" },
  { value: "belgian", label: "Belgian" },
  { value: "belizean", label: "Belizean" },
  { value: "beninese", label: "Beninese" },
  { value: "bermudian", label: "Bermudian" },
  { value: "bhutanese", label: "Bhutanese" },
  { value: "bolivian", label: "Bolivian" },
  { value: "bonairean", label: "Bonairean" },
  { value: "botswanan", label: "Botswanan" },
  { value: "brazilian", label: "Brazilian" },
  { value: "british", label: "British" },
  {
    value: "british_indian_ocean_territory",
    label: "British Indian Ocean Territory",
  },
  { value: "british_virgin_islander", label: "British Virgin Islander" },
  { value: "bruneian", label: "Bruneian" },
  { value: "burkinabe", label: "Burkinabe" },
  { value: "burmese", label: "Burmese" },
  { value: "cajun", label: "Cajun" },
  { value: "cambodian", label: "Cambodian" },
  { value: "cameroonian", label: "Cameroonian" },
  { value: "cape_verdean", label: "Cape Verdean" },
  { value: "caribbean", label: "Caribbean" },
  { value: "caymanian", label: "Caymanian" },
  { value: "central_african", label: "Central African" },
  { value: "central_american", label: "Central American" },
  { value: "chadian", label: "Chadian" },
  { value: "chilean", label: "Chilean" },
  { value: "chinese", label: "Chinese" },
  { value: "colombian", label: "Colombian" },
  { value: "congolese", label: "Congolese" },
  { value: "cook_islander", label: "Cook Islander" },
  { value: "costa_rican", label: "Costa Rican" },
  { value: "cuban", label: "Cuban" },
  { value: "curaçaoan", label: "Curaçaoan" },
  { value: "dominican", label: "Dominican" },
  { value: "east_timorese", label: "East Timorese" },
  { value: "eastern_european", label: "Eastern European" },
  { value: "ecuadorian", label: "Ecuadorian" },
  { value: "emirati", label: "Emirati" },
  { value: "equatoguinean", label: "Equatoguinean" },
  { value: "ethiopian", label: "Ethiopian" },
  { value: "falkland_islander", label: "Falkland Islander" },
  { value: "fijian", label: "Fijian" },
  { value: "filipino", label: "Filipino" },
  { value: "french", label: "French" },
  { value: "french_polynesian", label: "French Polynesian" },
  { value: "gabonese", label: "Gabonese" },
  { value: "gambian", label: "Gambian" },
  { value: "georgian", label: "Georgian" },
  { value: "german", label: "German" },
  { value: "ghanaian", label: "Ghanaian" },
  { value: "gibraltarian", label: "Gibraltarian" },
  { value: "greek", label: "Greek" },
  { value: "grenadian", label: "Grenadian" },
  { value: "guamanian", label: "Guamanian" },
  { value: "guatemalan", label: "Guatemalan" },
  { value: "guinean", label: "Guinean" },
  { value: "guinea_bissauan", label: "Guinea-Bissauan" },
  { value: "haitian", label: "Haitian" },
  { value: "honduran", label: "Honduran" },
  { value: "hong_kong", label: "Hong Kong" },
  { value: "hungarian", label: "Hungarian" },
  { value: "indian", label: "Indian" },
  { value: "indonesian", label: "Indonesian" },
  { value: "iranian", label: "Iranian" },
  { value: "iraqi", label: "Iraqi" },
  { value: "irish", label: "Irish" },
  { value: "israeli", label: "Israeli" },
  { value: "italian", label: "Italian" },
  { value: "ivorian", label: "Ivorian" },
  { value: "jamaican", label: "Jamaican" },
  { value: "japanese", label: "Japanese" },
  { value: "jordanian", label: "Jordanian" },
  { value: "kazakh", label: "Kazakh" },
  { value: "kenyan", label: "Kenyan" },
  { value: "kiribati", label: "Kiribati" },
  { value: "korean", label: "Korean" },
  { value: "kuwaiti", label: "Kuwaiti" },
  { value: "laotian", label: "Laotian" },
  { value: "latin_american", label: "Latin American" },
  { value: "lebanese", label: "Lebanese" },
  { value: "liberian", label: "Liberian" },
  { value: "libyan", label: "Libyan" },
  { value: "macanese", label: "Macanese" },
  { value: "madagascan", label: "Madagascan" },
  { value: "malawian", label: "Malawian" },
  { value: "malaysian", label: "Malaysian" },
  { value: "maldivian", label: "Maldivian" },
  { value: "malian", label: "Malian" },
  { value: "maltese", label: "Maltese" },
  { value: "marshallese", label: "Marshallese" },
  { value: "mauritian", label: "Mauritian" },
  { value: "mediterranean", label: "Mediterranean" },
  { value: "mexican", label: "Mexican" },
  { value: "micronesian", label: "Micronesian" },
  { value: "middle_eastern", label: "Middle Eastern" },
  { value: "miquelon", label: "Miquelon" },
  { value: "mongolian", label: "Mongolian" },
  { value: "montserratian", label: "Montserratian" },
  { value: "moroccan", label: "Moroccan" },
  { value: "mozambican", label: "Mozambican" },
  { value: "namibian", label: "Namibian" },
  { value: "nauruan", label: "Nauruan" },
  { value: "nepalese", label: "Nepalese" },
  { value: "nevisian", label: "Nevisian" },
  { value: "new_caledonian", label: "New Caledonian" },
  { value: "new_zealander", label: "New Zealander" },
  { value: "nicaraguan", label: "Nicaraguan" },
  { value: "nigerian", label: "Nigerian" },
  { value: "nigerien", label: "Nigerien" },
  { value: "niuean", label: "Niuean" },
  { value: "north_korean", label: "North Korean" },
  { value: "northern_marianan", label: "Northern Marianan" },
  { value: "omani", label: "Omani" },
  { value: "pakistani", label: "Pakistani" },
  { value: "palauan", label: "Palauan" },
  { value: "panamanian", label: "Panamanian" },
  { value: "papua_new_guinean", label: "Papua New Guinean" },
  { value: "paraguayan", label: "Paraguayan" },
  { value: "peruvian", label: "Peruvian" },
  { value: "polish", label: "Polish" },
  { value: "portuguese", label: "Portuguese" },
  { value: "puerto_rican", label: "Puerto Rican" },
  { value: "qatari", label: "Qatari" },
  { value: "romanian", label: "Romanian" },
  { value: "russian", label: "Russian" },
  { value: "rwandan", label: "Rwandan" },
  { value: "saban", label: "Saban" },
  { value: "saint_barthelemy", label: "Saint Barthelemy" },
  { value: "saint_helenian", label: "Saint Helenian" },
  { value: "saint_kittsian", label: "Saint Kittsian" },
  { value: "saint_lucian", label: "Saint Lucian" },
  { value: "saint_maartener", label: "Saint Maartener" },
  { value: "saint_martin", label: "Saint Martin" },
  { value: "saint_pierre", label: "Saint Pierre" },
  { value: "saint_vincentian", label: "Saint Vincentian" },
  { value: "salvadoran", label: "Salvadoran" },
  { value: "samoan", label: "Samoan" },
  { value: "saudi", label: "Saudi" },
  { value: "scandinavian", label: "Scandinavian" },
  { value: "senegalese", label: "Senegalese" },
  { value: "seychellois", label: "Seychellois" },
  { value: "sierra_leonean", label: "Sierra Leonean" },
  { value: "singaporean", label: "Singaporean" },
  { value: "sint_eustatius", label: "Sint Eustatius" },
  { value: "solomon_islander", label: "Solomon Islander" },
  { value: "somali", label: "Somali" },
  { value: "south_african", label: "South African" },
  { value: "south_american", label: "South American" },
  {
    value: "south_georgia_and_south_sandwich_islander",
    label: "South Georgia and South Sandwich Islander",
  },
  { value: "south_korean", label: "South Korean" },
  { value: "southern", label: "Southern" },
  { value: "spanish", label: "Spanish" },
  { value: "sri_lankan", label: "Sri Lankan" },
  { value: "sudanese", label: "Sudanese" },
  { value: "surinamese", label: "Surinamese" },
  { value: "swazi", label: "Swazi" },
  { value: "swedish", label: "Swedish" },
  { value: "swiss", label: "Swiss" },
  { value: "syrian", label: "Syrian" },
  { value: "taiwanese", label: "Taiwanese" },
  { value: "tanzanian", label: "Tanzanian" },
  { value: "thai", label: "Thai" },
  { value: "tibetan", label: "Tibetan" },
  { value: "tobagonian", label: "Tobagonian" },
  { value: "togolese", label: "Togolese" },
  { value: "tokelauan", label: "Tokelauan" },
  { value: "tongan", label: "Tongan" },
  { value: "trinidadian", label: "Trinidadian" },
  { value: "tristanian", label: "Tristanian" },
  { value: "tunisian", label: "Tunisian" },
  { value: "turkish", label: "Turkish" },
  { value: "turks_and_caicos_islander", label: "Turks and Caicos Islander" },
  { value: "tuvaluan", label: "Tuvaluan" },
  { value: "ugandan", label: "Ugandan" },
  { value: "ukrainian", label: "Ukrainian" },
  { value: "uruguayan", label: "Uruguayan" },
  { value: "uzbek", label: "Uzbek" },
  { value: "vanuatuan", label: "Vanuatuan" },
  { value: "venezuelan", label: "Venezuelan" },
  { value: "vietnamese", label: "Vietnamese" },
  { value: "virgin_islander", label: "Virgin Islander" },
  { value: "wallis_and_futunan", label: "Wallis and Futunan" },
  { value: "yemeni", label: "Yemeni" },
  { value: "zambian", label: "Zambian" },
  { value: "zimbabwean", label: "Zimbabwean" },
];

export const RECIPE_CATEGORIES = [
  { value: "appetizer", label: "Appetizer" },
  { value: "dessert", label: "Dessert" },
  { value: "main_course", label: "Main Course" },
];

export const RECIPE_DIFFICULTY = [
  { value: "easy", label: "Easy" },
  { value: "hard", label: "Hard" },
  { value: "medium", label: "Medium" },
];

export const RECIPE_MEAL_TYPES = [
  { value: "breakfast", label: "Breakfast" },
  { value: "dinner", label: "Dinner" },
  { value: "lunch", label: "Lunch" },
  { value: "snack", label: "Snack" },
  { value: "dessert", label: "Dessert" },
  { value: "drinks", label: "Drinks" },
];
